### ISSUE TITLE
Main Story

### ISSUE THREAD

**Issue by GraphicEdit** [MuKeDa/Project#13]

**Comment by Fishard** [comment]
BÖLÜM:1 

Laura ormanda gezintiye çıkmıştır. Bir süre yürüdüğünde yıllardır yaşadığı evin etrafında büyücüler ve bazı yaratıklar görür. Evini ve etrafı onlardan temizlemelidir. Hepsini öldürdüğünde boyut olarak oldukça büyük bir büyücüyle(kadın) karşılaşması gerekir. Büyücüyü yener fakat büyücü ölmemiştir. Bir portaldan açıp içine atlar, ardından Laura’yı da içeriye çeker.  

Savaşırken büyücü ve Laura arasındaki diyalog: 

1. İntikam vakti seni bücür! 

2. Beni öldüremeyeceksin! 

3. Ölmeye mahkumsun, bizim kaderimiz bu! 

Laura: 

1. Sen de kimsin? 

2. … 

3. Kader mi? Leila? Bu sen misin?  

Laura, portaldan içeriye çekilirken: “Hayıır!!!” 

 

BÖLÜM:2 

Leila etrafta görünmemektedir. Etrafta canlı hiçbir şey yoktur. Bu yerin karamsar ve renksiz bir havası vardır. Bir tuzakla karşılaşılır ve atlatılır. Ardından bir ev görünür. Evin önünde yaralandığı her halinden belli olan, yaşlı bir amca vardır.  

Yaşlı Amca: 

"O... Yıllardır bana yardım  

Ediyordu. Artık... onu tanı- 

Yamıyorum. "

(Ölür.) 

Laura 

"Hayır! Amca! Amca! Ne 

oldu ona?! Ah! Onu bul- 

malıyım!"

Laura biraz daha ilerler ve Leila’yı yeniden görür. Bu sefer ona saldırmamaktadır. Titremektedir.  

Leila: 

Bbb-ırak beni!!! 

O benim kardeşim! 

Hayır, hayır hayır! 

Ona zarar vermeyeceğim! 

Duydun mu beni! Başara- 

mayacaksın! 

(Çığlık atar ve büyük bir ışık hüzmesi         yayılıp ekranı kaplar.) 

Leila’dan geriye onun saydam bir gölgesi kalmıştır. Laura onunla savaşır ve kazanır. Ruh yok olunca Leila’nın yerde yattığı görülür.   

Laura: 

Kardeşim! İyi misin?  

Leila! HAYIR!!!  

Leila ölmüştür. 

Devam edecek...

**Comment by Ahmet8457haya** [comment]
kelimeler karışmş gibi. Oto düzeltmeden mi acaba?

**Comment by Fishard** [comment]
[https://docs.google.com/document/d/1DzlmrxXQWu6I-jgGH2C-da56DgJQ6pI_4rVooePkNe4/edit](url)
